[package]
name = "graph"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
percent-encoding.workspace = true
serde.workspace = true
serde_json.workspace = true
session.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
